# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc5bdbc6d2666f6dcae28499f3ec5e57ae82fb3bbdcce21bf5e79121bcf7efdc7cef4ffcb4901e93929ec331126f2fe924ddd246ac95f9677958426c2db5ceb3

test:
  secret_key_base: ba97c91eaee041d03b52abfd89c3649def7da9d51831759659b1aca93a6cd0a73794d2a34a6f87cbd713784779c8184e2e4ec275155dd30445caa771781348d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
